### ISSUE TITLE
properties -> yaml

### ISSUE THREAD

**Issue by zooneon** [Hanium-Cloud/room9-backend#27]
properties에서 yaml 파일로 바꾸는 거 어떻게 생각하시나요?
하다보니 프로파일 가독성이 너무 떨어져서,,
그리고 프로파일도 용도에 따라 나누면 좋을 것 같습니다!

**Comment by skehdxhd96** [comment]
전 찬성입니당

**Comment by hsju0202** [comment]
저도 좋습니다 :)
